
name: CI-CD

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Success
        run: echo "CI/CD workflow completed successfully"