name: CI-CD

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run success step
        run: echo "CI/CD workflow completed successfully"